-- Migration 012: 小学4年生 漢字読み問題シードデータ（102問）
-- 「{例文}」の「{漢字}」の読みをひらがなで答えよう

INSERT INTO questions (subject, format, input_type, body, answer, hint, unit, grade, kanji, source, use_count) VALUES
-- あ行
('japanese', 'reading', 'text', '「愛情」の「愛」の読みをひらがなで答えよう', 'あい', NULL, '漢字読み', 4, '愛', 'seed', 0),
('japanese', 'reading', 'text', '「案内」の「案」の読みをひらがなで答えよう', 'あん', NULL, '漢字読み', 4, '案', 'seed', 0),
('japanese', 'reading', 'text', '「以上」の「以」の読みをひらがなで答えよう', 'い', NULL, '漢字読み', 4, '以', 'seed', 0),
('japanese', 'reading', 'text', '「地位」の「位」の読みをひらがなで答えよう', 'い', NULL, '漢字読み', 4, '位', 'seed', 0),
('japanese', 'reading', 'text', '「印刷」の「印」の読みをひらがなで答えよう', 'いん', NULL, '漢字読み', 4, '印', 'seed', 0),
('japanese', 'reading', 'text', '「英語」の「英」の読みをひらがなで答えよう', 'えい', NULL, '漢字読み', 4, '英', 'seed', 0),
('japanese', 'reading', 'text', '「栄養」の「栄」の読みをひらがなで答えよう', 'えい', NULL, '漢字読み', 4, '栄', 'seed', 0),
('japanese', 'reading', 'text', '「食塩」の「塩」の読みをひらがなで答えよう', 'えん', NULL, '漢字読み', 4, '塩', 'seed', 0),
('japanese', 'reading', 'text', '「一億」の「億」の読みをひらがなで答えよう', 'おく', NULL, '漢字読み', 4, '億', 'seed', 0),
-- か行
('japanese', 'reading', 'text', '「加算」の「加」の読みをひらがなで答えよう', 'か', NULL, '漢字読み', 4, '加', 'seed', 0),
('japanese', 'reading', 'text', '「結果」の「果」の読みをひらがなで答えよう', 'か', NULL, '漢字読み', 4, '果', 'seed', 0),
('japanese', 'reading', 'text', '「課題」の「課」の読みをひらがなで答えよう', 'か', NULL, '漢字読み', 4, '課', 'seed', 0),
('japanese', 'reading', 'text', '「改正」の「改」の読みをひらがなで答えよう', 'かい', NULL, '漢字読み', 4, '改', 'seed', 0),
('japanese', 'reading', 'text', '「機械」の「械」の読みをひらがなで答えよう', 'かい', NULL, '漢字読み', 4, '械', 'seed', 0),
('japanese', 'reading', 'text', '「各地」の「各」の読みをひらがなで答えよう', 'かく', NULL, '漢字読み', 4, '各', 'seed', 0),
('japanese', 'reading', 'text', '「感覚」の「覚」の読みをひらがなで答えよう', 'かく', NULL, '漢字読み', 4, '覚', 'seed', 0),
('japanese', 'reading', 'text', '「完成」の「完」の読みをひらがなで答えよう', 'かん', NULL, '漢字読み', 4, '完', 'seed', 0),
('japanese', 'reading', 'text', '「官庁」の「官」の読みをひらがなで答えよう', 'かん', NULL, '漢字読み', 4, '官', 'seed', 0),
('japanese', 'reading', 'text', '「管理」の「管」の読みをひらがなで答えよう', 'かん', NULL, '漢字読み', 4, '管', 'seed', 0),
('japanese', 'reading', 'text', '「関係」の「関」の読みをひらがなで答えよう', 'かん', NULL, '漢字読み', 4, '関', 'seed', 0),
('japanese', 'reading', 'text', '「観察」の「観」の読みをひらがなで答えよう', 'かん', NULL, '漢字読み', 4, '観', 'seed', 0),
('japanese', 'reading', 'text', '「願書」の「願」の読みをひらがなで答えよう', 'がん', NULL, '漢字読み', 4, '願', 'seed', 0),
('japanese', 'reading', 'text', '「希望」の「希」の読みをひらがなで答えよう', 'き', NULL, '漢字読み', 4, '希', 'seed', 0),
('japanese', 'reading', 'text', '「季節」の「季」の読みをひらがなで答えよう', 'き', NULL, '漢字読み', 4, '季', 'seed', 0),
('japanese', 'reading', 'text', '「世紀」の「紀」の読みをひらがなで答えよう', 'き', NULL, '漢字読み', 4, '紀', 'seed', 0),
('japanese', 'reading', 'text', '「基礎」の「基」の読みをひらがなで答えよう', 'き', NULL, '漢字読み', 4, '基', 'seed', 0),
('japanese', 'reading', 'text', '「喜劇」の「喜」の読みをひらがなで答えよう', 'き', NULL, '漢字読み', 4, '喜', 'seed', 0),
('japanese', 'reading', 'text', '「国旗」の「旗」の読みをひらがなで答えよう', 'き', NULL, '漢字読み', 4, '旗', 'seed', 0),
('japanese', 'reading', 'text', '「器具」の「器」の読みをひらがなで答えよう', 'き', NULL, '漢字読み', 4, '器', 'seed', 0),
('japanese', 'reading', 'text', '「共通」の「共」の読みをひらがなで答えよう', 'きょう', NULL, '漢字読み', 4, '共', 'seed', 0),
('japanese', 'reading', 'text', '「協力」の「協」の読みをひらがなで答えよう', 'きょう', NULL, '漢字読み', 4, '協', 'seed', 0),
('japanese', 'reading', 'text', '「競争」の「競」の読みをひらがなで答えよう', 'きょう', NULL, '漢字読み', 4, '競', 'seed', 0),
('japanese', 'reading', 'text', '「極端」の「極」の読みをひらがなで答えよう', 'きょく', NULL, '漢字読み', 4, '極', 'seed', 0),
('japanese', 'reading', 'text', '「訓練」の「訓」の読みをひらがなで答えよう', 'くん', NULL, '漢字読み', 4, '訓', 'seed', 0),
('japanese', 'reading', 'text', '「軍隊」の「軍」の読みをひらがなで答えよう', 'ぐん', NULL, '漢字読み', 4, '軍', 'seed', 0),
('japanese', 'reading', 'text', '「光景」の「景」の読みをひらがなで答えよう', 'けい', NULL, '漢字読み', 4, '景', 'seed', 0),
('japanese', 'reading', 'text', '「芸術」の「芸」の読みをひらがなで答えよう', 'げい', NULL, '漢字読み', 4, '芸', 'seed', 0),
('japanese', 'reading', 'text', '「結論」の「結」の読みをひらがなで答えよう', 'けつ', NULL, '漢字読み', 4, '結', 'seed', 0),
('japanese', 'reading', 'text', '「建設」の「建」の読みをひらがなで答えよう', 'けん', NULL, '漢字読み', 4, '建', 'seed', 0),
('japanese', 'reading', 'text', '「健康」の「健」の読みをひらがなで答えよう', 'けん', NULL, '漢字読み', 4, '健', 'seed', 0),
('japanese', 'reading', 'text', '「経験」の「験」の読みをひらがなで答えよう', 'けん', NULL, '漢字読み', 4, '験', 'seed', 0),
('japanese', 'reading', 'text', '「成功」の「功」の読みをひらがなで答えよう', 'こう', NULL, '漢字読み', 4, '功', 'seed', 0),
('japanese', 'reading', 'text', '「気候」の「候」の読みをひらがなで答えよう', 'こう', NULL, '漢字読み', 4, '候', 'seed', 0),
-- さ行
('japanese', 'reading', 'text', '「差別」の「差」の読みをひらがなで答えよう', 'さ', NULL, '漢字読み', 4, '差', 'seed', 0),
('japanese', 'reading', 'text', '「最高」の「最」の読みをひらがなで答えよう', 'さい', NULL, '漢字読み', 4, '最', 'seed', 0),
('japanese', 'reading', 'text', '「材料」の「材」の読みをひらがなで答えよう', 'ざい', NULL, '漢字読み', 4, '材', 'seed', 0),
('japanese', 'reading', 'text', '「試験」の「試」の読みをひらがなで答えよう', 'し', NULL, '漢字読み', 4, '試', 'seed', 0),
('japanese', 'reading', 'text', '「治療」の「治」の読みをひらがなで答えよう', 'ち', NULL, '漢字読み', 4, '治', 'seed', 0),
('japanese', 'reading', 'text', '「辞書」の「辞」の読みをひらがなで答えよう', 'じ', NULL, '漢字読み', 4, '辞', 'seed', 0),
('japanese', 'reading', 'text', '「式典」の「式」の読みをひらがなで答えよう', 'しき', NULL, '漢字読み', 4, '式', 'seed', 0),
('japanese', 'reading', 'text', '「失礼」の「失」の読みをひらがなで答えよう', 'しつ', NULL, '漢字読み', 4, '失', 'seed', 0),
('japanese', 'reading', 'text', '「種類」の「種」の読みをひらがなで答えよう', 'しゅ', NULL, '漢字読み', 4, '種', 'seed', 0),
('japanese', 'reading', 'text', '「順番」の「順」の読みをひらがなで答えよう', 'じゅん', NULL, '漢字読み', 4, '順', 'seed', 0),
('japanese', 'reading', 'text', '「初日」の「初」の読みをひらがなで答えよう', 'しょ', NULL, '漢字読み', 4, '初', 'seed', 0),
('japanese', 'reading', 'text', '「合唱」の「唱」の読みをひらがなで答えよう', 'しょう', NULL, '漢字読み', 4, '唱', 'seed', 0),
('japanese', 'reading', 'text', '「印象」の「象」の読みをひらがなで答えよう', 'しょう', NULL, '漢字読み', 4, '象', 'seed', 0),
('japanese', 'reading', 'text', '「参照」の「照」の読みをひらがなで答えよう', 'しょう', NULL, '漢字読み', 4, '照', 'seed', 0),
('japanese', 'reading', 'text', '「信頼」の「信」の読みをひらがなで答えよう', 'しん', NULL, '漢字読み', 4, '信', 'seed', 0),
('japanese', 'reading', 'text', '「成長」の「成」の読みをひらがなで答えよう', 'せい', NULL, '漢字読み', 4, '成', 'seed', 0),
('japanese', 'reading', 'text', '「清潔」の「清」の読みをひらがなで答えよう', 'せい', NULL, '漢字読み', 4, '清', 'seed', 0),
('japanese', 'reading', 'text', '「静止」の「静」の読みをひらがなで答えよう', 'せい', NULL, '漢字読み', 4, '静', 'seed', 0),
('japanese', 'reading', 'text', '「面積」の「積」の読みをひらがなで答えよう', 'せき', NULL, '漢字読み', 4, '積', 'seed', 0),
('japanese', 'reading', 'text', '「節約」の「節」の読みをひらがなで答えよう', 'せつ', NULL, '漢字読み', 4, '節', 'seed', 0),
('japanese', 'reading', 'text', '「選挙」の「選」の読みをひらがなで答えよう', 'せん', NULL, '漢字読み', 4, '選', 'seed', 0),
('japanese', 'reading', 'text', '「戦争」の「戦」の読みをひらがなで答えよう', 'せん', NULL, '漢字読み', 4, '戦', 'seed', 0),
-- た行
('japanese', 'reading', 'text', '「辞典」の「典」の読みをひらがなで答えよう', 'てん', NULL, '漢字読み', 4, '典', 'seed', 0),
('japanese', 'reading', 'text', '「展示」の「展」の読みをひらがなで答えよう', 'てん', NULL, '漢字読み', 4, '展', 'seed', 0),
('japanese', 'reading', 'text', '「伝統」の「伝」の読みをひらがなで答えよう', 'でん', NULL, '漢字読み', 4, '伝', 'seed', 0),
('japanese', 'reading', 'text', '「特別」の「特」の読みをひらがなで答えよう', 'とく', NULL, '漢字読み', 4, '特', 'seed', 0),
('japanese', 'reading', 'text', '「得意」の「得」の読みをひらがなで答えよう', 'とく', NULL, '漢字読み', 4, '得', 'seed', 0),
-- な行
('japanese', 'reading', 'text', '「発熱」の「熱」の読みをひらがなで答えよう', 'ねつ', NULL, '漢字読み', 4, '熱', 'seed', 0),
('japanese', 'reading', 'text', '「記念」の「念」の読みをひらがなで答えよう', 'ねん', NULL, '漢字読み', 4, '念', 'seed', 0),
-- は行
('japanese', 'reading', 'text', '「失敗」の「敗」の読みをひらがなで答えよう', 'はい', NULL, '漢字読み', 4, '敗', 'seed', 0),
('japanese', 'reading', 'text', '「博物館」の「博」の読みをひらがなで答えよう', 'はく', NULL, '漢字読み', 4, '博', 'seed', 0),
('japanese', 'reading', 'text', '「ご飯」の「飯」の読みをひらがなで答えよう', 'はん', NULL, '漢字読み', 4, '飯', 'seed', 0),
('japanese', 'reading', 'text', '「飛行機」の「飛」の読みをひらがなで答えよう', 'ひ', NULL, '漢字読み', 4, '飛', 'seed', 0),
('japanese', 'reading', 'text', '「必要」の「必」の読みをひらがなで答えよう', 'ひつ', NULL, '漢字読み', 4, '必', 'seed', 0),
('japanese', 'reading', 'text', '「投票」の「票」の読みをひらがなで答えよう', 'ひょう', NULL, '漢字読み', 4, '票', 'seed', 0),
('japanese', 'reading', 'text', '「目標」の「標」の読みをひらがなで答えよう', 'ひょう', NULL, '漢字読み', 4, '標', 'seed', 0),
('japanese', 'reading', 'text', '「政府」の「府」の読みをひらがなで答えよう', 'ふ', NULL, '漢字読み', 4, '府', 'seed', 0),
('japanese', 'reading', 'text', '「兵隊」の「兵」の読みをひらがなで答えよう', 'へい', NULL, '漢字読み', 4, '兵', 'seed', 0),
('japanese', 'reading', 'text', '「変化」の「変」の読みをひらがなで答えよう', 'へん', NULL, '漢字読み', 4, '変', 'seed', 0),
('japanese', 'reading', 'text', '「便利」の「便」の読みをひらがなで答えよう', 'べん', NULL, '漢字読み', 4, '便', 'seed', 0),
('japanese', 'reading', 'text', '「方法」の「法」の読みをひらがなで答えよう', 'ほう', NULL, '漢字読み', 4, '法', 'seed', 0),
('japanese', 'reading', 'text', '「希望」の「望」の読みをひらがなで答えよう', 'ぼう', NULL, '漢字読み', 4, '望', 'seed', 0),
-- ま行
('japanese', 'reading', 'text', '「週末」の「末」の読みをひらがなで答えよう', 'まつ', NULL, '漢字読み', 4, '末', 'seed', 0),
('japanese', 'reading', 'text', '「満足」の「満」の読みをひらがなで答えよう', 'まん', NULL, '漢字読み', 4, '満', 'seed', 0),
('japanese', 'reading', 'text', '「未来」の「未」の読みをひらがなで答えよう', 'み', NULL, '漢字読み', 4, '未', 'seed', 0),
('japanese', 'reading', 'text', '「国民」の「民」の読みをひらがなで答えよう', 'みん', NULL, '漢字読み', 4, '民', 'seed', 0),
-- や行
('japanese', 'reading', 'text', '「約束」の「約」の読みをひらがなで答えよう', 'やく', NULL, '漢字読み', 4, '約', 'seed', 0),
('japanese', 'reading', 'text', '「勇気」の「勇」の読みをひらがなで答えよう', 'ゆう', NULL, '漢字読み', 4, '勇', 'seed', 0),
('japanese', 'reading', 'text', '「重要」の「要」の読みをひらがなで答えよう', 'よう', NULL, '漢字読み', 4, '要', 'seed', 0),
('japanese', 'reading', 'text', '「養育」の「養」の読みをひらがなで答えよう', 'よう', NULL, '漢字読み', 4, '養', 'seed', 0),
('japanese', 'reading', 'text', '「入浴」の「浴」の読みをひらがなで答えよう', 'よく', NULL, '漢字読み', 4, '浴', 'seed', 0),
-- ら行
('japanese', 'reading', 'text', '「便利」の「利」の読みをひらがなで答えよう', 'り', NULL, '漢字読み', 4, '利', 'seed', 0),
('japanese', 'reading', 'text', '「改良」の「良」の読みをひらがなで答えよう', 'りょう', NULL, '漢字読み', 4, '良', 'seed', 0),
('japanese', 'reading', 'text', '「料理」の「料」の読みをひらがなで答えよう', 'りょう', NULL, '漢字読み', 4, '料', 'seed', 0),
('japanese', 'reading', 'text', '「大量」の「量」の読みをひらがなで答えよう', 'りょう', NULL, '漢字読み', 4, '量', 'seed', 0),
('japanese', 'reading', 'text', '「種類」の「類」の読みをひらがなで答えよう', 'るい', NULL, '漢字読み', 4, '類', 'seed', 0),
('japanese', 'reading', 'text', '「命令」の「令」の読みをひらがなで答えよう', 'れい', NULL, '漢字読み', 4, '令', 'seed', 0),
('japanese', 'reading', 'text', '「冷蔵庫」の「冷」の読みをひらがなで答えよう', 'れい', NULL, '漢字読み', 4, '冷', 'seed', 0),
('japanese', 'reading', 'text', '「例文」の「例」の読みをひらがなで答えよう', 'れい', NULL, '漢字読み', 4, '例', 'seed', 0),
('japanese', 'reading', 'text', '「連絡」の「連」の読みをひらがなで答えよう', 'れん', NULL, '漢字読み', 4, '連', 'seed', 0),
('japanese', 'reading', 'text', '「老人」の「老」の読みをひらがなで答えよう', 'ろう', NULL, '漢字読み', 4, '老', 'seed', 0),
('japanese', 'reading', 'text', '「労働」の「労」の読みをひらがなで答えよう', 'ろう', NULL, '漢字読み', 4, '労', 'seed', 0),
('japanese', 'reading', 'text', '「記録」の「録」の読みをひらがなで答えよう', 'ろく', NULL, '漢字読み', 4, '録', 'seed', 0);
